[start_rss]
Name Test pkt
address http://filejunkie.livejournal.com/data/rss
template D:\hpt\rss2fido\rss2fido\template\lj.tpl
language D:\hpt\rss2fido\rss2fido\russian.lng

post_from test pkt
post_to "All"
post_faddress 2:5030/1543.33@fidonet
post_taddress 2:5030/1543@fidonet
post_subj "††"
post_origin "/(Kitten in Rainshire) (440-7701) (23:00-09:00)/"
post_flag  local

post_format pkt
post_base D:\inbound\hpt\
post_password passwd
post_area RAINSHIRE.LOCAL
[end_rss]

